/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEFVAR = 5;
  /** RegularExpression Id. */
  int DEFPROC = 6;
  /** RegularExpression Id. */
  int JUMP = 7;
  /** RegularExpression Id. */
  int TURN = 8;
  /** RegularExpression Id. */
  int GOTO = 9;
  /** RegularExpression Id. */
  int NOP = 10;
  /** RegularExpression Id. */
  int FACE = 11;
  /** RegularExpression Id. */
  int WITH = 12;
  /** RegularExpression Id. */
  int OFTYPE = 13;
  /** RegularExpression Id. */
  int TOTHE = 14;
  /** RegularExpression Id. */
  int INDIR = 15;
  /** RegularExpression Id. */
  int CARDINALDIR = 16;
  /** RegularExpression Id. */
  int DIRECTION = 17;
  /** RegularExpression Id. */
  int DIRECTIONCOMP = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int WHILE = 21;
  /** RegularExpression Id. */
  int REPEAT = 22;
  /** RegularExpression Id. */
  int EQUALS = 23;
  /** RegularExpression Id. */
  int FOR = 24;
  /** RegularExpression Id. */
  int DO = 25;
  /** RegularExpression Id. */
  int THEN = 26;
  /** RegularExpression Id. */
  int FACING = 27;
  /** RegularExpression Id. */
  int CANPUT = 28;
  /** RegularExpression Id. */
  int CANPICK = 29;
  /** RegularExpression Id. */
  int CANMOVE = 30;
  /** RegularExpression Id. */
  int CANJUMMP = 31;
  /** RegularExpression Id. */
  int NOT = 32;
  /** RegularExpression Id. */
  int MOV = 33;
  /** RegularExpression Id. */
  int RIGHT = 34;
  /** RegularExpression Id. */
  int PUT = 35;
  /** RegularExpression Id. */
  int PICK = 36;
  /** RegularExpression Id. */
  int POP = 37;
  /** RegularExpression Id. */
  int GO = 38;
  /** RegularExpression Id. */
  int HOP = 39;
  /** RegularExpression Id. */
  int BALLOONS = 40;
  /** RegularExpression Id. */
  int CHIPS = 41;
  /** RegularExpression Id. */
  int NUM = 42;
  /** RegularExpression Id. */
  int DIGIT = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"defVar\"",
    "\"defProc\"",
    "\"jump\"",
    "\"turn\"",
    "\"goto\"",
    "\"nop\"",
    "\"face\"",
    "\"with\"",
    "\"ofType\"",
    "\"toThe\"",
    "\"inDir\"",
    "<CARDINALDIR>",
    "<DIRECTION>",
    "<DIRECTIONCOMP>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"repeat\"",
    "\":=\"",
    "\"for\"",
    "\"do\"",
    "\"then\"",
    "\"facing\"",
    "\"canPut\"",
    "\"canPick\"",
    "\"canMove\"",
    "\"canJump\"",
    "\"not\"",
    "\"Mov\"",
    "\"RIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUM>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
  };

}
